version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: blog-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=192.168.100.30
      - DB_PORT=3306
      - DB_USERNAME=blog123
      - DB_PASSWORD=tonMotDePasse
      - DB_DATABASE=blog123
      - JWT_SECRET=unSecretJWTTresLong2024!
      - DB_SYNCHRONIZE=true

  frontend:
    build:
      context: ./frontend
    container_name: blog-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

# Ajoutez ici d'autres services (ex: base de données) si besoin
